import assert from 'node:assert/strict'
import test from 'node:test'
import JSZip from 'jszip'
import { JSDOM } from 'jsdom'
import * as XLSX from 'xlsx'
import { prepareWorkbenchOfficePreview, WORKBENCH_OFFICE_LIMITS, WorkbenchOfficePreviewError } from './workbenchOfficePreview'
import { preparePptxPreview, isCompletePptxRender } from './pptxPreview'

const dom = new JSDOM('')
Object.defineProperty(globalThis, 'DOMParser', { value: dom.window.DOMParser, configurable: true })
Object.defineProperty(globalThis, 'XMLSerializer', { value: dom.window.XMLSerializer, configurable: true })
test.after(() => dom.window.close())

const rels = (body: string) => `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${body}</Relationships>`
const rel = (target: string, mode = '') => `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${target}" ${mode}/>`
function presentation() {
  const zip = new JSZip()
  zip.file('[Content_Types].xml', '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"/>')
  zip.file('_rels/.rels', rels(rel('ppt/presentation.xml')))
  zip.file('ppt/presentation.xml', '<presentation/>')
  zip.file('ppt/slides/slide1.xml', '<slide/>')
  zip.file('ppt/slides/_rels/slide1.xml.rels', rels(rel('../media/image1.png')))
  zip.file('ppt/media/image1.png', new Uint8Array([137, 80, 78, 71]))
  return zip
}
async function blob(zip: JSZip) {
  return new Blob([await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' })])
}
function rejected(code: WorkbenchOfficePreviewError['code']) {
  return (error: unknown) => error instanceof WorkbenchOfficePreviewError && error.code === code
}

test('PPTX keeps slides, internal relative relationships, and embedded images', async () => {
  const zip = presentation()
  zip.file('ppt/slides/slide2.xml', '<slide>Second page</slide>')
  const result = await JSZip.loadAsync(await prepareWorkbenchOfficePreview(await blob(zip), 'pptx'))
  assert.equal(await result.file('ppt/slides/slide2.xml')?.async('text'), '<slide>Second page</slide>')
  assert.deepEqual(await result.file('ppt/media/image1.png')?.async('uint8array'), new Uint8Array([137, 80, 78, 71]))
  assert.equal(Object.values(result.files).some(entry => entry.dir), false)
})

test('validated workbench PPTX remains compatible with the upstream missing-master repair', async () => {
  const zip = presentation()
  const missing = '/ppt/slideMasters/slideMaster2.xml'
  zip.file('[Content_Types].xml', `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Override PartName="${missing}" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/></Types>`)
  zip.file('ppt/presentation.xml', '<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldIdLst><p:sldId id="256"/></p:sldIdLst></p:presentation>')
  const source = await blob(zip)
  const validated = await prepareWorkbenchOfficePreview(source, 'pptx')
  const prepared = await preparePptxPreview(validated)
  assert.equal(prepared.slideCount, 1)
  assert.equal(isCompletePptxRender({ slides: [{}] }, prepared.slideCount), true)
  const repaired = await JSZip.loadAsync(prepared.data)
  assert.ok(!(await repaired.file('[Content_Types].xml')!.async('string')).includes(missing))
  const original = await JSZip.loadAsync(await source.arrayBuffer())
  assert.ok((await original.file('[Content_Types].xml')!.async('string')).includes(missing))
  assert.equal(await repaired.file('ppt/slides/slide1.xml')!.async('string'), '<slide/>')
  assert.deepEqual(await repaired.file('ppt/media/image1.png')!.async('uint8array'), new Uint8Array([137, 80, 78, 71]))
})

test('XLSX generated by the existing spreadsheet library retains multiple sheets and cells', async () => {
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([['Backend', 'Count'], ['Docker', 7]]), 'Summary')
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([['Second sheet'], [42]]), 'Details')
  const source = new Blob([XLSX.write(workbook, { type: 'array', bookType: 'xlsx' })])
  const result = XLSX.read(await prepareWorkbenchOfficePreview(source, 'xlsx'), { type: 'array' })
  assert.deepEqual(result.SheetNames, ['Summary', 'Details'])
  assert.equal(result.Sheets.Summary.B2.v, 7)
  assert.equal(result.Sheets.Details.A2.v, 42)
})

for (const target of ['https://evil.example/image.png', '//evil.example/image.png', 'file:///etc/passwd', 'javascript:alert(1)', 'data:text/html,hello', 'https&#58;//evil.example/a', 'https%3a%2f%2fevil.example/a', '\\evil.example\\image']) {
  test(`Office rejects external target even without TargetMode: ${target}`, async () => {
    const zip = presentation()
    zip.file('ppt/slides/_rels/slide1.xml.rels', rels(rel(target)))
    await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'pptx'), rejected('officeExternal'))
  })
}

for (const path of ['_rels/.rels', 'ppt/slides/_rels/slide1.xml.rels', 'ppt/slideMasters/_rels/master.xml.rels', 'ppt/embeddings/_rels/attachment.xml.rels']) {
  test(`Office checks external relationships in every part: ${path}`, async () => {
    const zip = presentation()
    zip.file(path, rels(rel('/api/v1/auth/me', 'TargetMode="External"')))
    await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'pptx'), rejected('officeExternal'))
  })
}

test('XLSX external workbook links are rejected before the spreadsheet reader', async () => {
  const zip = presentation()
  zip.file('xl/workbook.xml', '<workbook/>')
  zip.file('xl/externalLinks/_rels/externalLink1.xml.rels', rels(rel('../linked.xlsx', 'TargetMode="External"')))
  await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'xlsx'), rejected('officeExternal'))
})

for (const path of ['../escape.xml', 'ppt/../../escape.xml', '/absolute.xml', 'ppt\\escape.xml', 'ppt/%2e%2e/escape.xml', 'C:/escape.xml']) {
  test(`Office rejects unsafe archive path: ${path}`, async () => {
    const zip = presentation()
    zip.file(path, '<unsafe/>', { createFolders: false })
    await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'pptx'), rejected('officeInvalid'))
  })
}

test('Office rejects escaping and missing internal relationships but accepts package-absolute targets', async () => {
  for (const target of ['../../../outside.xml', '%2e%2e/%2e%2e/%2e%2e/outside.xml', '/api/v1/auth/me', '../media/missing.png']) {
    const zip = presentation()
    zip.file('ppt/slides/_rels/slide1.xml.rels', rels(rel(target)))
    await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'pptx'), rejected('officeInvalid'))
  }
  const zip = presentation()
  zip.file('ppt/slides/_rels/slide1.xml.rels', rels(rel('/ppt/media/image1.png')))
  await prepareWorkbenchOfficePreview(await blob(zip), 'pptx')
})

test('Office rejects malformed packages, XML, DTDs, and entity expansion', async () => {
  await assert.rejects(prepareWorkbenchOfficePreview(new Blob(['not a zip']), 'pptx'), rejected('officeInvalid'))
  for (const xml of ['<broken>', '<!DOCTYPE x SYSTEM "https://evil.example/dtd"><x/>', '<!DOCTYPE x [<!ENTITY a "hello">]><x>&a;</x>']) {
    const zip = presentation()
    zip.file('ppt/slides/slide1.xml', xml)
    await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'pptx'), rejected('officeInvalid'))
  }
  await assert.rejects(prepareWorkbenchOfficePreview(await blob(presentation()), 'xlsx'), rejected('officeInvalid'))
})

test('Office bounds input size, entry count, and actual decompressed entry bytes', async () => {
  const normal = await blob(presentation())
  await assert.rejects(prepareWorkbenchOfficePreview(normal, 'pptx', normal.size - 1), rejected('officeTooLarge'))
  const many = presentation()
  for (let i = 0; i < WORKBENCH_OFFICE_LIMITS.entries; i++) many.file(`parts/${i}`, '', { createFolders: false })
  await assert.rejects(prepareWorkbenchOfficePreview(await blob(many), 'pptx'), rejected('officeTooLarge'))
  const large = presentation()
  large.file('large.bin', new Uint8Array(WORKBENCH_OFFICE_LIMITS.entryBytes + 1))
  const compressed = await blob(large)
  assert.ok(compressed.size < 20000)
  await assert.rejects(prepareWorkbenchOfficePreview(compressed, 'pptx'), rejected('officeTooLarge'))
})

test('Office bounds aggregate expanded bytes across individually acceptable entries', async () => {
  const zip = presentation()
  for (let i = 0; i < 5; i++) zip.file(`part${i}.bin`, new Uint8Array(WORKBENCH_OFFICE_LIMITS.entryBytes))
  await assert.rejects(prepareWorkbenchOfficePreview(await blob(zip), 'pptx'), rejected('officeTooLarge'))
})

test('Office expansion limits do not trust forged ZIP size headers', async () => {
  const zip = presentation()
  zip.file('large.bin', new Uint8Array(WORKBENCH_OFFICE_LIMITS.entryBytes + 1))
  const source = Buffer.from(await (await blob(zip)).arrayBuffer())
  let offset = source.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]))
  while (offset !== -1) {
    if (source.readUInt32LE(offset + 24) > WORKBENCH_OFFICE_LIMITS.entryBytes) source.writeUInt32LE(1, offset + 24)
    offset = source.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]), offset + 4)
  }
  await assert.rejects(prepareWorkbenchOfficePreview(new Blob([source]), 'pptx'), rejected('officeTooLarge'))
})

test('Office validation honors cancellation', async () => {
  const controller = new AbortController()
  controller.abort()
  await assert.rejects(prepareWorkbenchOfficePreview(await blob(presentation()), 'pptx', undefined, controller.signal), { name: 'AbortError' })
})
